name: ${project.name}
main: com.endercrest.voidspawn.VoidSpawn
version: ${project.version}
website: ${project.url}
description: Teleports player on contact with the void.
authors: [tcvs]
softdepend: [IslandWorld, ASkyblock, BentoBox, uSkyBlock]
api-version: 1.13
commands:
    voidspawn:
        description: All commands for voidspawn
        aliases: [vs, voidspawn]
permissions:
    vs.admin.mode:
        description: Grants you the /void mode command
        default: op
    vs.admin.reload:
        description: Grants you the /void reload command
        default: op
    vs.admin.remove:
        description: Grants you the /void remove command
        default: op
    vs.admin.set:
        description: Grants you the /void set command
        default: op
    vs.admin.help:
        description: Grants you the /void help command
        default: op
    vs.admin.message:
        description: Grants you the /void message command
        default: op
    vs.admin.offset:
        description: Grants you the /void offset command
        default: op
    vs.admin.command:
        description: Grants you the /void command command
        default: op
    vs.admin.keepinventory:
        description: Grants you the /void keepinventory command
        default: op
    vs.admin.hybrid:
        description: Grants you the /void hybrid command
        default: op
    vs.admin.detector:
        description: Grants you the /void detector command
        default: op
    vs.admin.sound:
        description: Grants you the /void sound command
        default: op
    vs.admin.status:
        description: Grants you the /void status command
        default: op
    vs.admin.*:
        description: Grants you the /void command
        default: op
        children:
            vs.admin.set: true
            vs.admin.reload: true
            vs.admin.remove: true
            vs.admin.mode: true
            vs.admin.help: true
            vs.admin.message: true
            vs.admin.offset: true
            vs.admin.command: true
            vs.admin.keepinventory: true
            vs.admin.hybrid: true
            vs.admin.detector: true
            vs.admin.status: true
    vs.enable:
      default: true
      description: Enables teleportation for the player
    vs.*:
        description: Gives all permissions
        default: false
        children:
            vs.admin.*: true
            vs.enable: true