version: 2

defaults: &defaults
  working_directory: ~/endercrest/VoidSpawn
  docker:
    - image: circleci/openjdk:8u171-jdk

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: voidspawn-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - run: mvn package -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: voidspawn-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: voidspawn-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo $(ls endercrest/VoidSpawn/target)
      - store_artifacts:
          path: target/VoidSpawn.jar
          destination: /Voidspawn.jar

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
